### PR TITLE
No need to enforce OpenGL anymore.

### PR DESCRIPTION
**Pull request by JamesMBallard**
# Description

Remove the enforcement of OpenGL in the daily sample builds. This will light up Direct3D on Windows and Metal for macOS/iOS.

Same change applies to individual samples.

### CODE REVIEW

**Review by GuillaumeBelz — APPROVED** [review]
A lot of samples! :)

LGFM

**Review by ldanzinger — APPROVED** [review]
spot checked, LGTM

**Review by tanneryould — APPROVED** [review]
LGTM, though do we need to remove OpenGL from the .pro files as well? For example: https://github.com/Esri/arcgis-maps-sdk-samples-qt/blob/v.next/ArcGISRuntimeSDKQt_CppSamples/DisplayInformation/DisplayGrid/DisplayGrid.pro#L25 has 

```
# additional modules are pulled in via arcgisruntime.pri
QT += opengl qml quick
```

**Comment by JamesMBallard** [comment]
@tanneryould that's a good question. I will log a new issue to look into that, but my hunch says that we still need it. All samples still retain the ability to support OpenGL even if they don't by default.

**Comment by GuillaumeBelz** [comment]
> we still need it

Maybe not. `opengl` module is used for `QOpenGLxxx` features, which is used but internally. I guess this is not used in samples and may be removed.

**Pull request merged**
