### PR TITLE
Jared/api key to access token

### PR DESCRIPTION
**Pull request by jared-2016**
# Description

update apikey terminology to use access token instead. Also renamed samples when being run standalone to not have ` - C++` included in it's name.

Also caught a few main signatures that deviated from the rest. Updated them so it's unified.

since i modified main.cpp files of individual samples, I picked 1/2 from each category and built them standalone and ran into no issues. Testing all 220 I think is unnecessary as the changes are all the same.

## Type of change

- [ ] Bug fix
- [ ] New sample implementation
- [ ] Sample viewer enhancement
- [x] Other enhancement

**Platforms tested on**:

- [ ] Windows
- [ ] Android
- [ ] Linux
- [x] macOS
- [ ] iOS

## Checklist

- [ ] Runs and compiles on all active platforms as a standalone sample
- [x] Runs and compiles in the sample viewer(s)
- [x] Branch is up to date with the latest main/v.next
- [ ] All merge conflicts have been resolved
- [x] Self-review of changes
- [ ] There are no warnings related to changes
- [ ] No unrelated changes have been made to any other code or project files
- [ ] Code is commented with correct formatting (CTRL+i)
- [ ] All variable and method names are camel case
- [ ] There is no leftover commented code
- [ ] Screenshots are correct size and display in description tab (500px by 500px, platform agnostic)
- [ ] If adding a new sample, it is added to the sample viewer
- [ ] Cherry-picked to Main branch (if applicable)

### CODE REVIEW

**Comment by jared-2016** [comment]
The templates have not been included in this PR as of right now.

The templates use a helper function to set the apikey(access token) but it also checks the command line to see if it was passed in that way. If this is something we wish to keep. It will require some reformatting from what the original issue requested it to be changed too. It's doable to find and replace it and put the forward declare and function implementation back. Seems like a luxury that I don't find most people doing.

for reference: https://github.com/Esri/arcgis-maps-sdk-samples-qt/blob/7c5d595b96a23f3deef70d59401413eb4f6170aa/Templates/CppSampleTemplate/main.cpp.tmpl#L85-L106

**Comment by jared-2016** [comment]
Also it's worth mentioning that it was never rolled out to all samples. We just updated the template at some point and started using it from there. If this is something we should decide to keep, we should update the samples to use this so the experience is consistent.

**Comment by JamesMBallard** [comment]
I agree with your assessment to just remove the command-line method of setting the API key. It was only there for a subset of samples, so we should make it official and consistent in the future if we want it. Good call.

**Review by JamesMBallard — APPROVED** [review]
I did a spot check. Looks good.

**Comment by jared-2016** [comment]
I updated templates which made me realize I forgot Widgets 😮

**Review by ldanzinger — APPROVED** [review]
LGTM

**Pull request merged**
